### ISSUE TITLE
Search searches forever

### ISSUE THREAD

**Issue by katyhuff** [pyne/pyne.github.com#2]
![image](https://cloud.githubusercontent.com/assets/393899/26606812/184aa39a-4559-11e7-8816-07d1952deb4c.png)

As in title. Search searches forever.

**Comment by skc222** [comment]
Rebuilding html files using `make html` from docs folder of pyne.github.com solves this issue. The only requirement is just that sphinx should be latest version. They have resolved this in their latest commit https://github.com/sphinx-doc/sphinx/commit/ff1adc7fd10bb2fc2ee021f55e9e121b2e69563e

I have rebuilt and used `make push-root` to push it on my fork. You can see changes on (search is working):
https://skc222.github.io/pyne.github.com/  

Please let me know if anything is wrong.

**Comment by katyhuff** [comment]
Your build looks good to me (and search works!). Please make a PR from skc222/pyne.github.com (master) to pyne/pyne.github.com (master) .

**Comment by katyhuff** [comment]
closed with #4
