### ISSUE TITLE
User's guide /enrichment: page broken

### ISSUE THREAD

**Issue by gridley** [pyne/pyne.github.com#6]
Take a look at usersguide/enrichment.html. This is pretty plainly broken, even just from looking in the source on github.

**Comment by katyhuff** [comment]
Thanks for reporting, @gridley ! Here's the full link: http://pyne.io/usersguide/enrichment.html . I wonder if this latex rendering error has wreaked any other havoc. It may just be a factor of a new build of the website. @skc222 has been improving the website this summer and may be able to debug this on her machine. What do you think, @skc222 ?

**Comment by skc222** [comment]
Yes..I will look into this. Sorry that I didn't notice this before

**Comment by katyhuff** [comment]
I didn't notice either. No worries!

**Comment by skc222** [comment]
This is the link of rebuilt website of my fork : https://skc222.github.io/pyne.github.com/
https://skc222.github.io/pyne.github.com/usersguide/enrichment.html seems to be correct now!
Please let me know if there is any other issue.
